### ISSUE TITLE
Matrix -> Telegram only sends first line of multiline message

### ISSUE THREAD

**Issue by L0ric0** [tulir/mautrix-telegram#309] opened 2019-04-10 17:39 UTC
The Bridge does only send the first line of a multiline message from matrix to telegram and ignores the rest. Will see if I can find the logs.

**Comment by tulir** [comment] 2019-04-11 10:49
Works fine for me with and without the relaybot and with and without formatting in the matrix message.

Make sure you're on the latest version. If it still happens, probably need some logs and preferably a reproducible test case.

**Comment by olmari** [comment] 2019-04-11 11:46
I have this happened too, Unfortunately no logs from that time but 3 screenshots from Riot(-android), Irssi and Telegram. Riot was also sending one, markdown enabled. I sent an youtube link with smiley "xD" on first line and then actual link in next line. I am not sure did I have single linefeed or 2 of them in between.

Riot showed it as normal multiline message:
![riot](https://user-images.githubusercontent.com/5422161/55954335-1b3ed400-5c67-11e9-9c16-f227c7fde8de.jpg)

Irssi showed it as 2 separate messages:
![irssi](https://user-images.githubusercontent.com/5422161/55954368-314c9480-5c67-11e9-886b-04ed6f80ac70.jpg)

While Telegram showed only the first line of the mesage:
![telegram](https://user-images.githubusercontent.com/5422161/55954403-49bcaf00-5c67-11e9-930a-9ca0406d2677.jpeg)

From these Telegram is only one that fails, whatever the reason or rootcause is.

All clients then showed the next message which was ircbot-generated URL-title.

Homeserver Synapse is version 0.99.3, Mautrix-telegram 0.5.1, Riot-android latest play-store offers and so on, everything should be up to date.

**Comment by tulir** [comment] 2019-04-11 13:08
Can't reproduce that either :/

**Comment by olmari** [comment] 2019-04-11 18:18
I am also logged in with matrix-login should that have some odd things that would change behaviour(?)

**Comment by mtippmann** [comment] 2019-04-11 21:59
can confirm that behavoir with 0.5.1  - I've seen it also happen for users that are not logged into telegram with their matrix-login. 

The respective messages had newlines between first and later lines, also bullet-points in later lines. Maybe it's useful - no logs unfortunatly.

**Comment by tulir** [comment] 2019-04-18 18:19
Looks like the problem is that Python's HTMLParser doesn't follow the HTML spec and handle tags like `<br>` as self-closing even when they're not self-closing. Probably need to override `handle_startendtag` and then add a check in [`handle_starttag`](https://github.com/tulir/mautrix-telegram/blob/master/mautrix_telegram/formatter/from_matrix/html_reader.py#L36-L39) to handle [void elements](http://w3c.github.io/html/single-page.html#void-elements)

**Comment by Ryonez** [comment] 2019-05-10 21:27
Just popping in as the missies and I just noticed this the last few days. 
So defiantly an issue still.

**Closed** 2019-05-11 18:55 UTC
Labels: bug: regression

**Comment by Ryonez** [comment] 2019-05-12 00:20
Thank you tulir, looks good now.
