### ISSUE TITLE
ValueError: no such name

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#255] opened 2018-12-16 20:52 UTC
```
[2018-12-16 20:50:14,033] [ERROR@mau.user] Failed to handle Telegram update
Traceback (most recent call last):
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 133, in _update_catch
    await self._update(update)
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 189, in _update
    await self.update_message(update)
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 382, in update_message
    return await portal.handle_telegram_message(self, sender, update)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 1504, in handle_telegram_message
    response = await self.handle_telegram_document(source, intent, evt, relates_to)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 1343, in handle_telegram_document
    info, name = self._parse_telegram_document_meta(evt, file, attrs)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 1306, in _parse_telegram_document_meta
    name = f"{alt} ({unicodedata.name(alt[0]).lower()})"
ValueError: no such name
```

Unknown cause or impact. Doesn't appear to have caused instability in the bridge, but equally Not Good.

**Comment by tulir** [comment] 2018-12-16 21:06
Duplicate of #252

**Closed by tulir** 2018-12-16 21:06 UTC
