### ISSUE TITLE
Option for changing the display name format of users who use the relay bot

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#151] opened 2018-06-07 17:59 UTC
Currently it seems to take the user's localpart in angled brackets. Would be nice to be able to say something like `**%displayName**` to end up with something like this:

> **TravisR**: Hello world!

**Comment by tulir** [comment] 2018-06-07 18:15
Duplicate of #92

**Comment by turt2live** [comment] 2018-06-07 18:16
oops sorry

**Closed by tulir** 2018-06-07 18:15 UTC
