### ISSUE TITLE
Bot doesn't gracefuly handle matrix puppet session logout

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#512] opened 2020-08-08 21:30 UTC
If you remove session from account (even if using auth secret shared token) bot doesn't try to reconnect nor inform user about logout.
There's just error on every request which would use this auth token/session:
```
mautrix-telegram_1   | [2020-08-08 21:27:35,681] [ERROR@mau.user.@test:matrix.test.juniorjpdj.pl] Failed to handle Telegram update UpdateNewChannelMessage(message=Message(id=494016, to_id=PeerChannel(channel_id=1146315424), date=datetime.datetime(2020, 8, 8, 21, 27, 35, 
tzinfo=datetime.timezone.utc), message='kek', out=True, mentioned=False, media_unread=False, silent=False, post=False, from_scheduled=False, legacy=False, edit_hide=False, from_id=834568015, fwd_from=None, via_bot_id=None, reply_to_msg_id=None, media=None, reply_markup=N
one, entities=[], views=None, edit_date=None, post_author=None, grouped_id=None, restriction_reason=[]), pts=510014, pts_count=1)                                                                                                                                              
mautrix-telegram_1   | Traceback (most recent call last):
mautrix-telegram_1   |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 196, in _update_catch
mautrix-telegram_1   |     await self._update(update)
mautrix-telegram_1   |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 243, in _update
mautrix-telegram_1   |     await self.update_message(update)
mautrix-telegram_1   |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 473, in update_message
mautrix-telegram_1   |     return await portal.handle_telegram_message(self, sender, update)
mautrix-telegram_1   |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 585, in handle_telegram_message
mautrix-telegram_1   |     event_id = await self.handle_telegram_text(source, intent, is_bot, evt)
mautrix-telegram_1   |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 281, in handle_telegram_text 
mautrix-telegram_1   |     return await self._send_message(intent, content, timestamp=evt.date)
mautrix-telegram_1   |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/portal.py", line 63, in _send_message
mautrix-telegram_1   |     return await intent.send_message_event(self.mxid, event_type, content, **kwargs)
mautrix-telegram_1   |   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 91, in wrapper
mautrix-telegram_1   |     return await __method(*args, **kwargs)
mautrix-telegram_1   |   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 270, in send_message_event
mautrix-telegram_1   |     return await super().send_message_event(room_id, event_type, content, **kwargs)
mautrix-telegram_1   |   File "/usr/lib/python3.8/site-packages/mautrix/client/api/events.py", line 296, in send_message_event
mautrix-telegram_1   |     resp = await self.api.request(Method.PUT, url, content, **kwargs)
mautrix-telegram_1   |   File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 205, in request
mautrix-telegram_1   |     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-telegram_1   |   File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 144, in _send
mautrix-telegram_1   |     raise make_request_error(http_status=response.status,
mautrix-telegram_1   | mautrix.errors.request.MUnknownToken: Unrecognised access token
```

**Comment by tulir** [comment] 2020-08-08 21:39
Duplicate of #439

**Closed by tulir** 2020-08-08 21:39 UTC
