### ISSUE TITLE
matrix.MatrixHandler.handle_part() makes invalid method call

### ISSUE THREAD

**Issue by V02460** [tulir/mautrix-telegram#222] opened 2018-09-08 09:43 UTC
There is a code path that should break when it is taken:

https://github.com/tulir/mautrix-telegram/blob/d35104aea63c9d1a3c7a3f0c963dc6cb4bde10da/mautrix_telegram/matrix.py#L202-L205

The method [`portal.Portal.leave_matrix()`](https://github.com/tulir/mautrix-telegram/blob/d35104aea63c9d1a3c7a3f0c963dc6cb4bde10da/mautrix_telegram/portal.py#L751) does take a `User` as first argument, but we pass in a `Puppet`. The method is not able to handle a `Puppet` object, so this should given an error.

I am not sure about the right solution here. I see some possibilities:

1. There might already be a right method which can be used in this case instead
2. `Puppet` and `User` should share a common Base class which is used in `portal.Portal.leave_matrix()`
3. `portal.Portal.leave_matrix()` should be rewritten to take both types

**Comment by tulir** [comment] 2018-11-15 09:53
Probably duplicate of #191

**Closed by tulir** 2018-11-15 09:53 UTC
Labels: bug
