### ISSUE TITLE
Another "the bridge hasn't received the decryption keys" style error

### ISSUE THREAD

**Issue by heini** [tulir/mautrix-telegram#563] opened 2020-12-22 13:04 UTC
I also see this kind of error (as in #562), with current telegram bridge and synapse server. However, the reason why I see this seems to be a database problem, since I have this in the bridge log (redacted):
```
[2020-12-22 13:54:44,508] [ERROR@mau.user.@user:server] Failed to automatically enable custom puppet
Traceback (most recent call last):
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 3 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/mautrix_telegram/user.py", line 244, in post_login
    await puppet.switch_mxid(access_token="auto", mxid=self.mxid)
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/mautrix/bridge/custom_puppet.py", line 211, in switch_mxid
    await self.save()
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/mautrix_telegram/puppet.py", line 174, in save
    self.db_instance.edit(**self._fields)
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/mautrix/util/db/base.py", line 159, in edit
    .values(**values))
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/opt/venvs/matrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 3 - probably unsupported type.
[SQL: UPDATE puppet SET custom_mxid=?, access_token=?, next_batch=?, base_url=?, displayname=?, displayname_source=?, username=?, photo_id=?, is_bot=?, matrix_registered=?, disable_updates=? WHERE puppet.id = ?]
[parameters: ('@user:server', 'the_token', 's3805_57294_0_530_604_4_585_2918_2', URL('https://server'), None, None, None, None, 0, 1, 0, 403928596)]
(Background on this error at: http://sqlalche.me/e/13/rvf5)
```

**Comment by tulir** [comment] 2020-12-22 13:10
duplicate of #546

**Closed by tulir** 2020-12-22 13:10 UTC

**Comment by heini** [comment] 2020-12-22 13:37
Oh, didn't see this one. Indeed, the code change mentioned there seems to resolve it (at least the stack trace doesn't appear anymore...
