### ISSUE TITLE
Messages in Telegram Channels are not bridged to Matrix

### ISSUE THREAD

**Issue by stfnnklv** [tulir/mautrix-telegram#436] opened 2020-03-03 15:48 UTC
Hello,

In version 0.7.1, messages posted in telegram channels are not bridged to Matrix. There is an exception in the log:
```
[ERROR@mau.user.@snikolov:<channel>] Failed to handle Telegram update UpdateNewChannelMessage(message=Message(id=3234, to_id=PeerChannel(channel_id=1234567890), date=datetime.datetime(2020, 3, 3, 15, 33, 47, tzinfo=datetime.timezone.utc), message='Test', out=False, mentioned=False, media_unread=False, silent=False, post=True, from_scheduled=False, legacy=False, edit_hide=False, from_id=None, fwd_from=None, via_bot_id=None, reply_to_msg_id=None, media=None, reply_markup=None, entities=[], views=1, edit_date=None, post_author='Stefan Nikolov', grouped_id=None, restriction_reason=[]), pts=3557, pts_count=1)
Traceback (most recent call last):
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/abstract_user.py", line 194, in _update_catch
    await self._update(update)
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/abstract_user.py", line 241, in _update
    await self.update_message(update)
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/abstract_user.py", line 424, in update_message
    if self.ignore_incoming_bot_events and self.relaybot and sender.id == self.relaybot.tgid:
AttributeError: 'NoneType' object has no attribute 'id'

```

Kind regards,
Stefan Nikolov

**Comment by tulir** [comment] 2020-03-03 15:52
Duplicate of #417 

(already fixed, use v0.7.2-rc1)

**Closed by tulir** 2020-03-03 15:52 UTC
