### ISSUE TITLE
Missing photo on telegram server stops backfill

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#480] opened 2020-06-10 20:23 UTC
When photo is missing on telegram server (old group chat) backfill crashes.
For example my backfill crashed with message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 359, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/commands/handler.py", line 130, in _run_handler
    return await handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 253, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/commands/telegram/misc.py", line 340, in backfill
    await portal.backfill(evt.sender)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 425, in backfill
    await self.handle_telegram_message(source, sender, message)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 495, in handle_telegram_message
    event_id = await {
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 76, in handle_telegram_photo
    loc, largest_size = self._get_largest_photo_size(evt.media.photo)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/base.py", line 214, in _get_largest_photo_size
    largest = max(photo.thumbs if isinstance(photo, Document) else photo.sizes,
AttributeError: 'PhotoEmpty' object has no attribute 'sizes'
```
Also.. I'll not be able to resume this backfill after fix, I'll need to recreate bridged group.

**Comment by tulir** [comment] 2020-07-29 19:15
Looks like #494 was a duplicate of this and was fixed

**Closed by tulir** 2020-07-29 19:15 UTC
