### ISSUE TITLE
Implement dynamic reloading of bridge permissions list without full restarting of bridge

### ISSUE THREAD

**Issue by MurzNN** [tulir/mautrix-telegram#617] opened 2021-05-01 13:29 UTC
On my setups I have the script, that dynamically manage list of user permissions for bridge (`bridge permissions` section of main `config.yaml` file). But the problem is that for apply changes I need to do a full restart of bridge.

The restart itself is not a problem, but the problem is that all users receive "reconnected" messages on all their puppets each time when I change permissions policy, that is too noisy for other users. Also at restart time bridge can lose some messages, I guess.

So will be good to implement any way to dynamically reload of permission rules, without restarting of bridge and reconnecting of puppets for users, whose permissions are not changed.

And maybe good idea is to store permissions info separately from main config file, maybe even in database?

**Comment by tulir** [comment] 2021-05-01 13:31
Duplicate of #224

**Closed by tulir** 2021-05-01 13:31 UTC
