### ISSUE TITLE
Random "Can't reconnect until invalid transaction is rolled back" errors

### ISSUE THREAD

**Issue by ananace** [tulir/mautrix-telegram#269] opened 2019-01-23 16:03 UTC
Every now and then, something seems to fail in the bridge, resulting in a SQLAlchemy exception;

```
[2019-01-23 15:02:38,547] [ERROR@mau.fmt.tg] Failed to convert Telegram format:
message=[REDACTED]
entities=[<telethon.tl.types.MessageEntityMention object at 0x7f75ba33b7b8>]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1125, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 427, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mautrix-telegram/mautrix_telegram/formatter/from_telegram.py", line 219, in _telegram_entities_to_matrix_catch
    return _telegram_entities_to_matrix(text, entities)
  File "/opt/mautrix-telegram/mautrix_telegram/formatter/from_telegram.py", line 254, in _telegram_entities_to_matrix
    skip_entity = _parse_mention(html, entity_text)
  File "/opt/mautrix-telegram/mautrix_telegram/formatter/from_telegram.py", line 287, in _parse_mention
    user = u.User.find_by_username(username) or pu.Puppet.find_by_username(username)
  File "/opt/mautrix-telegram/mautrix_telegram/user.py", line 397, in find_by_username
    puppet = DBUser.query.filter(DBUser.tg_username == username).one_or_none()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2854, in one_or_none
    ret = list(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2925, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2948, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1132, in _execute_context
    None, None)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1125, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 427, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT "user".mxid AS user_mxid, "user".tgid AS user_tgid, "user".tg_username AS user_tg_username, "user".tg_phone AS user_tg_phone, "user".saved_contacts AS user_saved_contacts \nFROM "user" \nWHERE "user".tg_username = %(tg_username_1)s'] [parameters: [{}]]
```

This is with the bridge running against a PostgreSQL 9.6 server.

The error itself seems to cause a message/event to be lost, but the bridge itself seems to keep running fine afterwards.

**Comment by tulir** [comment] 2019-02-11 23:22
That error seems to be just one caused by the SQLAlchemy ORM getting stuck after a bad transaction, so not that useful. I think #263 is basically the same thing and can be fixed by reducing orm usage or adding checks or rollbacks

**Closed by tulir** 2019-02-11 23:22 UTC
