### ISSUE TITLE
After logout + login bot fails to bridge DMs

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#522] opened 2020-09-14 06:57 UTC
At some point I invalidated session on telegram side,
I had to logout, bridge kicked me off from all chats and after relogin...
It fails to join DMs back.
Group chats work good.

**Comment by JuniorJPDJ** [comment] 2020-09-19 14:17
It still creates new DMs when I start writing with new person.
It fails to create/invite me to DMs which were created before logout.

**Comment by tulir** [comment] 2020-11-10 23:30
Probably duplicate of #397

**Closed** 2020-11-11 01:11 UTC
Labels: bug: defect
